// TODO
const ADD_TODO = 'ADD_TODO';
const FETCH_TODOS = 'FETCH_TODOS';
const FETCH_TODO = 'FETCH_TODO';
const DELETE_TODO = 'DELETE_TODO';
const UPDATE_TODO = 'UPDATE_TODO';

// MODAL
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';

// ERROR
const IS_ERROR = 'IS_ERROR';

// ETC
const IS_FOCUSED = 'IS_FOCUSED';

export {
  // TODO
  ADD_TODO,
  FETCH_TODOS,
  FETCH_TODO,
  DELETE_TODO,
  UPDATE_TODO,
  // MODAL
  SHOW_MODAL,
  HIDE_MODAL,
  // ERROR
  IS_ERROR,
  // ETC
  IS_FOCUSED,
};
