// TODO
const ADD_TODO = 'ADD_TODO';
const FETCH_TODO = 'FETCH_TODO';
const DELETE_TODO = 'DELETE_TODO';
const UPDATE_TODO = 'UPDATE_TODO';

// MODAL
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';

export {
  // TODO
  ADD_TODO,
  FETCH_TODO,
  DELETE_TODO,
  UPDATE_TODO,
  // MODAL
  SHOW_MODAL,
  HIDE_MODAL,
};
